"""New alembic

Revision ID: 39970eb69cbc
Revises:
Create Date: 2025-07-07 17:51:42.868531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39970eb69cbc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_status",
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "delivery_types",
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("delivery_floor", sa.Integer(), nullable=False),
        sa.Column("delivery_price", sa.Integer(), nullable=False),
        sa.Column("price_for_floor", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "main_rooms",
        sa.Column("room", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products_types",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("imageURL", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promo_action",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("percent", sa.Integer(), nullable=False),
        sa.Column("fix_price", sa.Integer(), nullable=False),
        sa.Column("date_of_finish", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("user_name", sa.String(length=20), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "orders",
        sa.Column(
            "order_date",
            sa.DateTime(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("products_id", sa.PickleType(), nullable=False),
        sa.Column("promo_id", sa.Integer(), nullable=True),
        sa.Column("user_name", sa.String(), nullable=True),
        sa.Column("delivery_type_id", sa.Integer(), nullable=False),
        sa.Column("delivery_address", sa.Text(), nullable=True),
        sa.Column("user_phone", sa.String(), nullable=False),
        sa.Column("user_email", sa.String(), nullable=True),
        sa.Column("order_confirmation_by_admin", sa.Boolean(), nullable=False),
        sa.Column("order_payment", sa.Boolean(), nullable=False),
        sa.Column("order_delivery_status", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["delivery_type_id"],
            ["delivery_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promo_id"],
            ["promo_action.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("imageURL", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("availability", sa.Integer(), nullable=False),
        sa.Column("allImagesURL", sa.PickleType(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["products_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["main_rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_history",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(TIMEZONE('utc', now()))"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("request_history", sa.String(), nullable=False),
        sa.Column("order_history", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_history")
    op.drop_table("products")
    op.drop_table("orders")
    op.drop_table("users")
    op.drop_table("promo_action")
    op.drop_table("products_types")
    op.drop_table("main_rooms")
    op.drop_table("delivery_types")
    op.drop_table("delivery_status")
    # ### end Alembic commands ###
