"""Initial revision

Revision ID: 5fa8a827e38d
Revises: 
Create Date: 2025-06-30 17:27:07.865834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa8a827e38d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('imageURL', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('fix_price', sa.Integer(), nullable=False),
    sa.Column('date_of_finish', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('products_id', sa.PickleType(), nullable=False),
    sa.Column('promo_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('delivery_type_id', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('order_confirmation_by_admin', sa.Boolean(), nullable=False),
    sa.Column('order_payment', sa.Boolean(), nullable=False),
    sa.Column('order_delivery_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['delivery_types.id'], ),
    sa.ForeignKeyConstraint(['promo_id'], ['promo_action.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imageURL', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('availability', sa.Integer(), nullable=False),
    sa.Column('allImagesURL', sa.PickleType(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_type_id'], ['products_types.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['main_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('request_history', sa.PickleType(), nullable=False),
    sa.Column('order_history', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_history')
    op.drop_table('products_list')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('promo_action')
    op.drop_table('products_types')
    op.drop_table('main_rooms')
    op.drop_table('delivery_types')
    op.drop_table('delivery_status')
    # ### end Alembic commands ###
